# Generated by Django 5.2.6 on 2025-09-24 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('sipuni', 'Sipuni'), ('dadata', 'Dadata'), ('proxy_market', 'Proxy Market'), ('timeweb', 'TimeWeb'), ('farpost', 'Farpost'), ('yandex_cloud', 'Yandex Cloud'), ('proxyline', 'ProxyLine')], max_length=255)),
                ('api_key', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='RUB', max_length=10)),
                ('subscription_end', models.DateTimeField(blank=True, null=True)),
                ('tokens_remaining', models.IntegerField(blank=True, null=True)),
                ('proxies_count', models.IntegerField(blank=True, null=True)),
                ('hours_left', models.IntegerField(blank=True, null=True)),
                ('active_proxies_count', models.IntegerField(blank=True, null=True)),
                ('companies_count', models.IntegerField(blank=True, null=True)),
                ('license_date_end', models.DateTimeField(blank=True, null=True)),
                ('user_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('raw_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service')),
            ],
        ),
        migrations.CreateModel(
            name='FarpostCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('ads_count', models.IntegerField(default=0)),
                ('ads_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farpost_companies', to='services.servicedata')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceDataHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service')),
            ],
        ),
    ]
