# Generated by Django 5.2.6 on 2025-09-24 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_delete_farpostcompany'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='service',
            name='type',
        ),
        migrations.RemoveField(
            model_name='servicedata',
            name='companies_count',
        ),
        migrations.RemoveField(
            model_name='servicedata',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='servicedata',
            name='user_name',
        ),
        migrations.AddField(
            model_name='servicedata',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicedata',
            name='total_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
