# Generated by Django 5.2.6 on 2025-09-24 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_remove_service_duration_remove_service_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicedata',
            name='license_date_end',
        ),
    ]
