# Generated by Django 5.2.6 on 2025-09-24 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_remove_servicedata_license_date_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedata',
            name='hourly_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicedata',
            name='monthly_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
