# Generated by Django 5.2.6 on 2025-09-24 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_servicedata_hourly_cost_servicedata_monthly_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicedata',
            name='updated_at',
        ),
    ]
