# Generated by Django 5.2.6 on 2025-09-25 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_remove_servicedata_updated_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceDataHistory',
        ),
    ]
